services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: bharatfd_backend
    ports:
      - "80:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
