# Generated by Django 5.1.5 on 2025-02-01 11:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[
                 ('hi', 'Hindi'), ('bn', 'Bengali')], max_length=10)),
                ('question', models.TextField()),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='translations', to='home.faq')),
            ],
            options={
                'db_table': 'faq_translations',
                'unique_together': {('faq', 'language')},
            },
        ),
    ]
